#!/bin/bash

function join { local IFS="$1"; shift; echo "$*"; }
function nodes { echo `cat namelist.input | grep node$1 | tr -s " " | cut -d " " -f4 | sed "s/,$//"`; }

NX=`nodes "x"`
NY=`nodes "y"`

echo "Running with" $NX "x" $NY "=" $((NX * NY)) "nodes on:"
for h in $@
do
	echo -e "\t$h"
done

echo "Copying namelist.input to hosts."
for h in $@
do
	scp namelist.input $h:`pwd`/namelist.input
done

mpirun --prefix /usr/local --host `join , $@` -np $((NX * NY)) cm1
